# All SpaceVim option below [option] section
[options]

# Disable guicolors in basic mode, many terminal do not support 24bit
# true colors
enable_guicolors = true
colorscheme = "bubblegum"
custom_color_palette = [
    ['#282C34', '#98C379', 114, 235],
    ['#ABB2BF', '#3E4452', 236, 144],
    ['#ABB2BF', '#3B4048', 238, 144],
    ['#5C6370', 59],
    ['#282c34', '#00af87', 235, 36],
    ['#282c34', '#ff8700', 235, 208],
    ['#282c34', '#af5f5f', 235, 131],
    ['#282828', '#689d6a', 235, 72],
    ['#282828', '#8f3f71', 235, 132]
]

# Set the statusline separators of statusline, default is "arrow"
statusline_separator = "arrow"
# Set the statusline separators of inactive statusline
statusline_iseparator = "arrow"

enable_tabline_filetype_icon = true

windows_leader = "²"

filetree_direction = "left"

lint_engine = "ale"

[[layers]]
name = 'core'
enable_smooth_scrolling = false

[[layers]]
name = "core#banner"

[[layers]]
name = "colorscheme"

[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name ='gtags'

[[layers]]
name = "leaderf"

[[layers]]
name = 'lang#java'

[[layers]]
name = "lang#toml"

[[layers]]
name = "lang#plantuml"

[[layers]]
name = "lang#python"
enabled_linters = ['pylint']

# [[layers]]
# name = 'lsp'
# enabled_clients = ['pyright']

[[layers]]
name = "lang#dockerfile"

[[layers]]
name = "lang#powershell"

[[layers]]
name = "lang#xml"

[[custom_plugins]]
repo = "martinda/Jenkinsfile-vim-syntax"
merged = false

[[layers]]
name = "git"
git_plugin = "fugitive"

[[custom_plugins]]
repo = "tpope/vim-sleuth"
merged = false

[[custom_plugins]]
repo = "robbles/logstash.vim"
merged = false

[[custom_plugins]]
repo = "pearofducks/ansible-vim"
merged = false

[[custom_plugins]]
repo = "chr4/nginx.vim"
merged = false
